spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://omar2301433_db_user:omarMIU2023@food.6piqnyt.mongodb.net/food_ordering_system?retryWrites=true&w=majority
spring.data.mongodb.database=food
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omartimo33@gmail.com
spring.mail.password=oyyipukkxyxortrb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

