spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://omar2301433_db_user:omarMIU2023@food.6piqnyt.mongodb.net/food_ordering_system?retryWrites=true&w=majority
spring.data.mongodb.database=food
